### ISSUE TITLE
Use node-mapnik for test image fixture comparision

### ISSUE THREAD

**Issue by yhahn** [mapbox/node-mapbox-gl-native#100]
Suggestion: avoid shelling out to imagemagick's `compare` to compare images to expected fixtures.

This is done in `assert-http` using node-mapnik here:

https://github.com/mapbox/assert-http/blob/master/index.js#L298-L320

Might be worth splitting this out into its own module even (`assert-image`, maybe per https://github.com/mapbox/assert-http/issues/4) and just sharing it between projects.

cc @samanpwbb @mikemorris

**Comment by jfirebaugh** [comment]
We also use imagemagick to generate a diff between expected and actual images so you can see what's off. I'd love to have a native solution for that too so we can drop the imagemagick dependency everywhere mapbox-gl-test-suite is used (here, -js, and -native).

**Comment by mikemorris** [comment]
I would love to split this out into an `assert-image` module. Pulling in all of `node-mapnik` for a single image comparison is far too much overhead.

**Comment by flippmoke** [comment]
You know there is an `Mapnik.Image.Compare` method? 

https://github.com/mapnik/node-mapnik/blob/master/test/image.test.js#L534-L567

**Comment by mikemorris** [comment]
Possible we'll find a solution to this in https://github.com/mapbox/mapbox-gl-test-suite/issues/24
