### ISSUE TITLE
lat/lng don't work, should be replaced by center

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/node-mapbox-gl-native#101]
docs need to be updated, lat/lng seem to have no effect on map renders.

**Comment by mikemorris** [comment]
Docs updated in https://github.com/mapbox/node-mapbox-gl-native/commit/ffc937b18476304a4833ba6728a94c5f6f178973. Need to confirm that this is passed to `mapbox-gl-native` correctly internally as per https://github.com/mapbox/mapbox-gl-native/issues/97

**Comment by mikemorris** [comment]
Looks like `center: [{latitude}, {longitude}]` is [parsed correctly](https://github.com/mapbox/node-mapbox-gl-native/blob/ffc937b18476304a4833ba6728a94c5f6f178973/src/node_map.cpp#L148-L150)
