### ISSUE TITLE
text label rendering problems 

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/node-mapbox-gl-native#106]
Seems like characters that are rotated end up with black gaps around their bounding boxes:

![screen shot 2015-03-24 at 12 56 44 pm](https://cloud.githubusercontent.com/assets/108094/6807516/490f7b4e-d225-11e4-9d90-17d0e9a5cba0.png)

**Comment by mikemorris** [comment]
This is probably an upstream issue, maybe related to https://github.com/mapbox/mapbox-gl-native/issues/957?

**Comment by mikemorris** [comment]
Possible this has already been fixed upstream, but node-mbgl is still pinned against the [`static-render`](https://github.com/mapbox/mapbox-gl-native/tree/static-render) branch for now.

**Comment by mikemorris** [comment]
Doesn't look like tracking mbgl `master` fixes this.

![screen shot 2015-04-17 at 4 10 37 pm](https://cloud.githubusercontent.com/assets/1149913/7203653/614c81de-e51c-11e4-8304-772c0b484b60.png)

**Comment by mikemorris** [comment]
Seems to be happening far less frequently now that we're tracking gl-native `master` again, but this bug is still present.
![screen shot 2015-04-17 at 4 17 51 pm](https://cloud.githubusercontent.com/assets/1149913/7203776/75f5b9a6-e51d-11e4-8fdb-4484b208e425.png)

**Comment by mikemorris** [comment]
Outdated.
