### ISSUE TITLE
missing labels

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/node-mapbox-gl-native#117]
Lack of labels is suspicious:

https://api-gl-staging.tilestream.net/styles/v1/saman/saman.19cc5727/-77.0164,38.9047,6/300x600@2x.png?access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww

Some sort of rendering issue.

**Comment by mikemorris** [comment]
Think this was caused by Glyph PBFs not loading in time due to https://github.com/mapbox/mapbox-gl-native/pull/1523, please reopen if reproducible.
