### ISSUE TITLE
Access other Mapbox GL APIs?

### ISSUE THREAD

**Issue by jleppert** [mapbox/node-mapbox-gl-native#120]
Are there any plans to have access to the other APIs of Mapbox GL native, specifically the map.project APIs, the same ones that are available via the native javascript client?

**Comment by mikemorris** [comment]
Current plans here are just to provide a lightweight wrapper for rendering rasters from GL in Node.js, additional functionality may be considered if there's a compelling use case.

Functionality like `map.project` can be better handled by standalone libs such as [node-sphericalmercator](https://github.com/mapbox/node-sphericalmercator) though.

**Comment by jleppert** [comment]
My use case is I needed to access some of the methods that are exposed via the standard API to do drawing on the map (i.e. within a node canvas). I found a workaround, but it's less than ideal and it would be nice to use the same methods that I have access to in my javascript code. I had assumed the interface would be the same.

**Comment by jleppert** [comment]
Here is my work-around to access those methods in the same way Mapbox client side works (so I can assure the same results) in case anyone needs it:

```javascript
var Transform    = require('mapbox-gl/js/geo/transform'),
	LatLng       = require('mapbox-gl/js/geo/lat_lng'),
	LatLngBounds = require('mapbox-gl/js/geo/lat_lng_bounds');

var transform = new Transform(opts.minZoom || 0, opts.maxZoom || 20);

	transform.center = LatLng.convert(opts.center);
	transform.width = opts.width;
	transform.height = opts.height;
	transform.zoom = opts.zoom;

	if (opts.maxBounds) {
		var b = LatLngBounds.convert(opts.maxBounds);
		transform.latRange = [b.getSouth(), b.getNorth()];
		transform.lngRange = [b.getWest(), b.getEast()];
	}

	transform._constrain();

var unProjected = transform.locationPoint(LatLng.convert([opts.geo.lat, opts.geo.lng]));
```

**Comment by mikemorris** [comment]
@jleppert You should be able to find examples of the projection math you're looking for in the [mapbox/abaculus](https://github.com/mapbox/abaculus/blob/master/index.js) project.
