### ISSUE TITLE
Error: 403 status code downloading tarball

### ISSUE THREAD

**Issue by cappelaere** [mapbox/node-mapbox-gl-native#126]
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v1.0.3/node-v14-darwin-x64.tar.gz

**Comment by mikemorris** [comment]
No binary published yet for Node.js 0.12.x (`process.versions.modules === 14`, see packaging script in node-pre-gyp at https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/versioning.js#L32-L50 for details).

We just landed support in `master` for Node.js 0.12.x and io.js and are working to fix a few crashes before tagging a new release. In the meantime, you can try installing under Node.js 0.10.x or pulling down the `master` branch and running `npm install --build-from-source`.
