### ISSUE TITLE
propagate `exception.what()` when rendering fails

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/node-mapbox-gl-native#139]
Currently a failed render from node-mbgl comes out with the generic message "Error rendering image". However, more diagnostics are available from the [`std::exception_ptr`](http://en.cppreference.com/w/cpp/error/exception_ptr) that `NodeMap` has access to [here](https://github.com/mapbox/node-mapbox-gl-native/blob/efb583186f73140b137739eb7b2ede3d86389574/src/node_map.cpp#L231-L239).

**Comment by mikemorris** [comment]
@tmpsantos started on this in https://github.com/mapbox/node-mapbox-gl-native/pull/134
