### ISSUE TITLE
Recycle View objects instead of resizing

### ISSUE THREAD

**Issue by mikemorris** [mapbox/node-mapbox-gl-native#142]
> We should have different views with a fixed size, and swap a map object's view as needed

Possibly implement this as an LRU cache keyed on dimensions? Per https://github.com/mapbox/node-mapbox-gl-native/issues/12#issuecomment-61333518, not sure if we should implement this in here or just expose the `View` object and implement the LRU cache/pooling downstream in tilelive-gl like https://github.com/mapbox/tilelive-gl/pull/36 - thoughts @yhahn @kkaefer?

Needed to adapt to changes from https://github.com/mapbox/mapbox-gl-native/pull/1799.

**Comment by mikemorris** [comment]
Started looking into this more, and I'm not currently seeing any way to assign a new `View` to a `Map` or to access `view.getFramebufferSize` (which is looks like are the dimensions used for `Still` rendering). Is this functionality that needs to be added or am I going about this the wrong way?

**Comment by kkaefer** [comment]
> Possibly implement this as an LRU cache keyed on dimensions?

Yes.

> I'm not currently seeing any way to assign a new View to a Map

There is none, but we can add one.

**Comment by mikemorris** [comment]
Starting upstream work in https://github.com/mapbox/mapbox-gl-native/pull/1964

**Comment by mikemorris** [comment]
> expose the View object and implement the LRU cache/pooling downstream in tilelive-gl

^ going with this plan

**Comment by jfirebaugh** [comment]
Per chat, I feel pretty strongly that we should do the opposite -- resize the HeadlessViews as needed and cache only `Map` objects downstream, keyed on style and pixel ratio.

**Comment by kkaefer** [comment]
@jfirebaugh Resizing a headless view takes almost the same amount of time as it does to make a completely new one, since the framebuffer needs to be reallocated.

**Comment by mikemorris** [comment]
Opting for https://github.com/mapbox/node-mapbox-gl-native/pull/147 as a simpler solution now, may revisit later.
