### ISSUE TITLE
Mark as deprecated

### ISSUE THREAD

**Issue by tmcw** [mapbox/node-mapbox-gl-native#151]
Over at [mapbox gl native](https://github.com/mapbox/mapbox-gl-native/pull/1289) and in offline conversations, people decided that this repo will be folded into mapbox-gl-native. @mikemorris is rolling a patch and will reference this issue once he opens a PR.

We need to make it clear what the fate of this repository will be, to make this conversation properly communicated beyond those in chat at that instant, and to discourage people from contributing patches here and direct them to contributing over at mapbox-gl-native.

**Comment by mikemorris** [comment]
Refs https://github.com/mapbox/mapbox-gl-native/pull/2179

**Comment by mikemorris** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/2179 has been merged, [`v2.0.0-pre.3`](https://www.npmjs.com/package/mapbox-gl-native) has been published to npm and this repository has been [marked as deprecated](https://github.com/mapbox/node-mapbox-gl-native/commit/7092d1c60362d4c66f9272f5fe72f1823bdf0a80)
