### ISSUE TITLE
Support for 404 tiles

### ISSUE THREAD

**Issue by vicapow** [mapbox/node-mapbox-gl-native#152]
Mapbox API returns 404 for tiles that don't exist. example: 

https://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/6/0/56.vector.pbf?access_token=$mapboxAccessToken

```json
{"message":"Tile does not exist"}
```
But it doesn't seem possible to properly handler this in the file source handlers.

If we return an object:
````js
    } else if (res.statusCode === 404) {
      req.respond(null, {data: null});
    }
````

    TypeError: Response data must be a Buffer

If we instead send `{}` instead of `{data: null}` the map render callback never gets called.

**Comment by mikemorris** [comment]
We're using the following snippet to render a blank tile if the vector tile doesn't exist:
```
if (res.statusCode === 404 && req.kind === 3) {
    req.respond(null, {});
}
```
`req.kind === 3` denotes a tile request as per https://github.com/mapbox/mapbox-gl-native/tree/master/platform/node#implementing-a-file-source

We've also just finished migrating the Node.js bindings into the core mapbox-gl-native project, and tagged a pre-release `v2.0.0-pre.3` (with `node-pre-gyp` binaries only, source build from `npm install` isn't working yet), which changes the `FileSource` implementation a bit - you might want to check that out if the above code isn't working still.
