### ISSUE TITLE
How to adapt code around v8 changes?

### ISSUE THREAD

**Issue by mikemorris** [mapbox/node-mapbox-gl-native#87]
Currently using `UV_VERSION_MAJOR` and `UV_VERSION_MINOR` as a hacky stopgap - what would be the proper way to do this? I'm specifically running into trouble around `v8::UniquePersistent`, which isn't in NAN yet.
 
Curious as to your current techniques re https://github.com/joyent/node/issues/5789 @springmeyer 

The NAN defines like [`NODE_0_10_MODULE_VERSION`](https://github.com/rvagg/nan/blob/master/nan.h#L56-L60) don't seem to be available to me for some reason, should I use `NODE_MODULE_VERSION` or `NODE_VERSION_AT_LEAST(major, minor, patch)`?

https://github.com/joyent/node/blob/master/src/node_version.h
https://github.com/iojs/io.js/blob/v1.x/src/node_version.h

**Comment by mikemorris** [comment]
https://github.com/mapbox/node-pre-gyp/commit/a859ec518778888486aec3f95803147faf0975d8 looks like it could provide some guidance here, refs https://github.com/mapbox/node-pre-gyp/issues/150

**Comment by springmeyer** [comment]
don't see that as related @mikemorris

**Comment by mikemorris** [comment]
Simply needed to `#include <node_version.h>` to check `NODE_MODULE_VERSION`.
