### ISSUE TITLE
`dyld: Library not loaded: /usr/local/lib/libpng15.15.dylib` in test results

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/node-mapbox-gl-native#92]
Getting a weird error when i try to run tests. Test output looks good, but:

![screen shot 2015-02-25 at 2 24 13 pm](https://cloud.githubusercontent.com/assets/108094/6378522/f8df1cdc-bcf9-11e4-8256-a11943f55378.png)

**Comment by mikemorris** [comment]
Run `brew info imagemagick` - looks like it might not be built properly with `libpng` and `freetype` support.

For reference, mine looks like this:
```
==> Dependencies
Build: xz ✔, pkg-config ✔
Required: libtool ✔, xz ✔
Recommended: jpeg ✔, libpng ✔, freetype ✔
Optional: fontconfig ✔, libtiff ✔, little-cms ✘, little-cms2 ✔, libwmf ✘, librsvg ✘, liblqr ✘, openexr ✘, ghostscript ✘, webp ✔, fftw ✘
```

**Comment by samanpwbb** [comment]
This is an issue with my imagemagick
