### ISSUE TITLE
add tests and documentation expecting gzipped vector tile protobuf responses

### ISSUE THREAD

**Issue by mikemorris** [mapbox/node-mapbox-gl-native#95]
These must be handled by `FileSource` uncompressed internally, but are served gzip-compressed by the Mapbox API servers. An example fix would be setting the [`gzip: true`](https://github.com/request/request#requestoptions-callback) option when using the [`request`](https://github.com/request/request) module.

**Comment by mikemorris** [comment]
Let's test this by adding a `.pbf.gz` version of https://github.com/mapbox/node-mapbox-gl-native/blob/master/test/fixtures/tiles/0-0-0.vector.pbf and adding some tests that spin up a static file server with [st](https://github.com/isaacs/st) then use [request](https://github.com/request/request) a gzipped vector tile.

**Comment by samanpwbb** [comment]
@mikemorris i started trying to figure this out in https://github.com/mapbox/node-mapbox-gl-native/tree/test-gzip but there are a bunch of pieces that I don't understand. Can we talk first thing tomorrow mornig?

**Comment by samanpwbb** [comment]
@mikemorris I was distracted all day today, so just now got around to this. Still struggling. I made notes in three places where I'm running into trouble: https://github.com/mapbox/node-mapbox-gl-native/blob/9045cdd6fa98d9f62ed533f58c51404c8bd0f4cc/test/map-gz.test.js#L15, https://github.com/mapbox/node-mapbox-gl-native/blob/9045cdd6fa98d9f62ed533f58c51404c8bd0f4cc/test/map-gz.test.js#L58, https://github.com/mapbox/node-mapbox-gl-native/blob/9045cdd6fa98d9f62ed533f58c51404c8bd0f4cc/test/map-gz.test.js#L79

Lets talk tomorrow morning!

**Comment by mikemorris** [comment]
Opened a pull request at https://github.com/mapbox/node-mapbox-gl-native/pull/98 so I can do inline comments.
